# Generated by Django 3.0.3 on 2020-03-01 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import glasgo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to=glasgo.models.image_path)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('price_range', models.CharField(blank=True, choices=[('FR', 'Free'), ('CH', 'Cheap'), ('MO', 'Moderate'), ('EX', 'Expensive')], max_length=2)),
                ('family_friendly', models.BooleanField(default=False)),
                ('disabled_access', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('multi_language', models.BooleanField(default=False)),
                ('starts', models.DateTimeField(blank=True)),
                ('ends', models.DateTimeField(blank=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasgo.Attraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('mutex_tags', models.ManyToManyField(related_name='_tag_mutex_tags_+', to='glasgo.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='attraction',
            name='tags',
            field=models.ManyToManyField(to='glasgo.Tag'),
        ),
    ]
