# Generated by Django 3.0.3 on 2020-03-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='price_range',
            field=models.CharField(blank=True, choices=[('FR', 'Free'), ('CH', 'Cheap'), ('MO', 'Moderate'), ('EX', 'Expensive')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='starts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
