# Generated by Django 3.0.3 on 2020-03-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgo', '0002_auto_20200301_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
