attractions = {
    "Celtic Park Stadium": {
        "link": "http://www.celticfc.net/mainindex",
        "image": "https://cdn.getyourguide.com/img/tour_img-1222909-148.jpg",
        "description": "Celtic Park in the Parkhead area of Glasgow, Scotland, is the home ground of Celtic Football Club. With a capacity of 60,411, it is the largest football stadium in Scotland, and the eighth-largest stadium in the United Kingdom. It is known by Celtic fans as Parkhead or Paradise.",
        "location": "Celtic Park Stadium, The Celtic Way, Parkhead, Glasgow, G40 3RE",
        "price_range": "MO",
        "family_friendly": True,
        "disabled_access": True,
        "parking": True,
        "multi_language": False,
        "tags": ["Sports", "Cultural Landmark",],
    },
    "George Square": {
        "image": "https://upload.wikimedia.org/wikipedia/commons/a/ad/City_Chambers%2C_George_Square%2C_Glasgow_05.jpg",
        "description": "George Square is the principal civic square in the city of Glasgow, Scotland. It is one of six squares in the city centre, the others being Cathedral Square, St Andrew's Square, St Enoch Square, Royal Exchange Square, and Blythswood Square on Blythswood Hill.",
        "location": "George Square, Glasgow, G2 1DH",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": False,
        "multi_language": False,
        "tags": ["Cultural Landmark", "Monument",],
    },
    "Kelvingrove Art Gallery and Museum": {
        "image": "https://peoplemakeglasgow.com/images/Things_to_do/Museums_and_galleries/Kelvingrove-995.jpg",
        "description": "Kelvingrove Art Gallery and Museum is a museum and art gallery in Glasgow, Scotland. It reopened in 2006 after a three-year refurbishment and since then has been one of Scotland's most popular visitor attractions. The museum has 22 galleries, housing a range of exhibits, including Renaissance art, taxidermy, and artifacts from ancient Egypt.",
        "location": "Kelvingrove Art Gallery and Museum, Argyle St, Glasgow, G3 8AG",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": False,
        "multi_language": True,
        "tags": ["Cultural Landmark", "Museum", "Art Gallery",],
    },
    "Glasgow Cathedral": {
        "image": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Glasgow_Cathedral_%28HDR%29_%288038797339%29.jpg",
        "description": "Glasgow Cathedral, also called the High Kirk of Glasgow or St Kentigern's or St Mungo's Cathedral, is the oldest cathedral on mainland Scotland and is the oldest building in Glasgow. Since the Reformation the cathedral continues in public ownership, within the responsibility of Historic Environment Scotland. The congregation is part of the Church of Scotland's Presbytery of Glasgow and its services and associations are open to all. ",
        "location": "Cathedral Precinct, Castle Street, Glasgow, G4 0QZ",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": False,
        "multi_language": True,
        "tags": ["Cultural Landmark", "Monument", "Historic",],
    },
    "Glasgow Botanic Gardens": {
        "image": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fz7qBF2oVac0%2Fmaxresdefault.jpg&f=1&nofb=1",
        "description": "Glasgow Botanic Gardens is a botanical garden located in the West End of Glasgow, Scotland. It features several glasshouses, the most notable of which is the Kibble Palace. The Gardens has a wide variety of temperate and tropical flora, a herb garden, a chronological bed with plants arranged according to their introduction to Scotland, the UK's national collection of tree ferns, and a world rose garden officially opened in 2003 by Princess Tomohito of Mikasa.",
        "location": "730 Great Western Road, Glasgow, G12 0UE",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": False,
        "multi_language": True,
        "tags": ["Natural Landmark", "Park",],
    },
    "Pollock Country Park": {
        "image": "https://peoplemakeglasgow.com/images/Things_to_do/Parks_and_gardens/PollokHouse-995.jpg",
        "description": "The park is Glasgow's largest park and the only Country Park within Glasgow. Its extensive woodlands and gardens provide a quiet sanctuary for both visitors and wildlife. The park is rich in rural history formerly being part of the Old Pollok Estate and ancestral home to the Maxwell Family. The park is also home to the world famous Burrell Collection.",
        "location": "2060 Pollokshaws Road, Glasgow, G43 1AT",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": True,
        "multi_language": True,
        "tags": ["Natural Landmark", "Cultural Landmark", "Park",],
    },
    "The Riverside Museum of Transport and Travel": {
        "image": "https://media-cdn.tripadvisor.com/media/photo-s/05/29/a9/44/the-riverside-museum.jpg",
        "description": "Riverside Museum is Glasgow's award-winning transport museum. With over 3,000 objects on display there's everything from skateboards to locomotives, paintings to prams and cars to a Stormtrooper. There are over 90 large touch screens panels full of images, memories and films that tell the fascinating stories behind the objects.",
        "location": "100 Pointhouse Place, Glasgow, G3 8RS",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": True,
        "multi_language": True,
        "tags": ["Cultural Landmark", "Museum"],
    },
    "University of Glasgow": {
        "image": "https://www.telegraph.co.uk/content/dam/education/2016/08/01/21590241universityofglasgowm-xlarge_trans_NvBQzQNjv4BqvHvVfV1SJqTMKlHaE5FBlnzInX02uMnPr3P1UZfzc14.jpg",
        "description": "The University of Glasgow is a public research university in Glasgow, Scotland. Founded by papal bull in 1451, it is the fourth-oldest university in the English-speaking world and one of Scotland's four ancient universities. Along with the universities of Edinburgh, Aberdeen, and St Andrews, the university was part of the Scottish Enlightenment during the 18th century. ",
        "location": "University Avenue, West End, Glasgow, G12 8QQ",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": True,
        "multi_language": True,
        "tags": ["Cultural Landmark", "Historic",],
    },
    "Tennents Wellpark Brewery": {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Tennents_Brewery.jpg/1200px-Tennents_Brewery.jpg",
        "description": "Wellpark Brewery in Glasgow is home to more than 450 years of brewing tradition and award winning beers. This is a chance to learn about the rich heritage of one of the country's most loved brands as well as about the production processes that have taken place at Wellpark from through the centuries up to today. ",
        "location": "161 Duke Street, Glasgow, G31 1JD",
        "price_range": "",
        "family_friendly": True,
        "disabled_access": False,
        "parking": True,
        "multi_language": False,
        "tags": ["Cultural Landmark",],
    },
    "The Necropolis": {
        "image": "https://assets.atlasobscura.com/media/W1siZiIsInVwbG9hZHMvcGxhY2VfaW1hZ2VzL2EzNjkzMjlhMmM2Y2Y1MTdiMzM3NTI3NjU1MTIzMWVjN2ZmOTU2ZTkuanBnIl0sWyJwIiwiY29udmVydCIsIi1xdWFsaXR5IDkxIC1hdXRvLW9yaWVudCJdLFsicCIsInRodW1iIiwiNjAweD4iXV0/a369329a2c6cf517b3375276551231ec7ff956e9.jpg",
        "description": "The Glasgow Necropolis is a Victorian cemetery in Glasgow, Scotland. It is on a low but very prominent hill to the east of Glasgow Cathedral (St. Mungo's Cathedral). Fifty thousand individuals have been buried here. Typical for the period, only a small percentage are named on monuments and not every grave has a stone. Approximately 3500 monuments exist here. ",
        "location": "50 Cathedral Square, Glasgow, G4 0UZ",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": False,
        "parking": True,
        "multi_language": False,
        "tags": ["Cultural Landmark", "Park", "Historic",],
    },
    "The Mackintosh House": {
        "image": "https://www.gla.ac.uk/media/Media_531136_smxx.jpg",
        "description": "The Mackintosh House is a meticulous reassemblage of the principal interiors from the Mackintoshes’ Glasgow home. The couple lived at 78 Southpark Avenue (originally 6 Florentine Terrace) from 1906 to 1914. Substantial alterations were made in 1906 as Mackintosh remodelled the proportions and natural lighting of the Victorian end-of-terrace house. The principal interiors were decorated in his distinctive style, remarkable then, and now, for the disciplined austerity of the furnishings and decoration.  ",
        "location": "82 Hillhead Street, Glasgow, G12 8QE",
        "price_range": "CH",
        "family_friendly": True,
        "disabled_access": False,
        "parking": False,
        "multi_language": False,
        "tags": ["Cultural Landmark", "Historic",],
    },
    "Glasgow Science Centre": {
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Glasgow_Science_Centre_and_Tower.jpg/1024px-Glasgow_Science_Centre_and_Tower.jpg",
        "description": "Glasgow Science Centre is a visitor attraction located in the Clyde Waterfront Regeneration area on the south bank of the River Clyde in Glasgow, Scotland. Queen Elizabeth II opened Glasgow Science Centre on 5 July 2001. It is one of Scotland's most popular paid-for visitor attractions. It is a purpose-built science centre composed of three principal buildings: Science Mall, Glasgow Tower and an IMAX cinema.  ",
        "location": "50 Pacific Quay, Glasgow, G51 1EA",
        "price_range": "MO",
        "family_friendly": True,
        "disabled_access": True,
        "parking": True,
        "multi_language": True,
        "tags": ["Museum",],
    },
    "The Tenement House": {
        "image": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fkingfishervisitorguides.com%2Fglasgow%2Fwp-content%2Fuploads%2F2016%2F08%2FThe-Tenement-House_.jpg&f=1&nofb=1",
        "description": "The Tenement House is a National Trust for Scotland property in Glasgow's City Centre. With 1892 original features it provides a rare glimpse into life in Glasgow in the early 20th century. ",
        "location": "145 Buccleuch Street, Glasgow, G3 6QN",
        "price_range": "CH",
        "family_friendly": True,
        "disabled_access": True,
        "parking": False,
        "multi_language": False,
        "tags": ["Cultural Landmark", "Historic", "Museum",],
    },
    "People's Palace and Winter Gardens": {
        "image": "https://prodglportalv2.azureedge.net/cache/9/9/9/f/d/d/999fdd47ccb23fc992e922f212777f78cece67d0.jpg",
        "description": "The People's Palace and Winter Gardens, set in historic Glasgow Green, the oldest public space in the city, tells the story of Glasgow and its people from 1750 to the end of the 20th century. Adjacent to the People's Palace is the extravagant and recently restored Doulton Fountain, unveiled in 1888 to commemorate Queen Victoria's Golden Jubilee.",
        "location": "Glasgow Green, Glasgow, G40 1AT",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": False,
        "multi_language": False,
        "tags": ["Cultural Landmark", "Museum", "Historic",],
    },
    "Glasgow Green": {
        "image": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpeoplemakeglasgow.com%2Fimages%2FThings_to_do%2FFood_and_drink%2FPicnic%2FGlasgow-Green-995x500.jpg&f=1&nofb=1",
        "description": "One of the oldest and most historic parks in Scotland stretches from the Saltmarket at the High Court across to the Calton and Bridgeton districts, and was used mainly for sheep and cattle grazing until the nineteenth century.",
        "location": "90 Greendyke Street, Glasgow, G1 5DB",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": False,
        "multi_language": True,
        "tags": ["Park", "Historic",],
    },
    "Glasgow Police Museum": {
        "image": "https://peoplemakeglasgow.com/images/Top_Reasons_To_Visit/Glasgow_Police_Museum.jpg",
        "description": "The Glasgow Police Museum illustrates the history of the Glasgow Police 1779 - 1975, through artifacts, stories and images.",
        "location": "30 Bell Street, Glasgow, G1 1LG",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": False,
        "multi_language": False,
        "tags": ["Museum",],
    },
    "Hunterian Museum": {
        "image": "https://www.gla.ac.uk/media/Media_591822_smxx.jpg",
        "description": "The Hunterian is Scotland's oldest public museum and home to one of the largest collections outside the National Museums. The Hunterian is one of the leading university museums in the world and its collections have been Recognised as a Collection of National Significance. It is one of Scotland’s most important cultural assets.‌",
        "location": "Glasgow University, University Avenue, Glasgow, G12 8QQ, ",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": True,
        "multi_language": False,
        "tags": ["Museum", "Historic", "Cultural Landmark",],
    },
    "Kelvingrove Park": {
        "image": "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2F4.bp.blogspot.com%2F-4Y7vxIwu55g%2FVTk8vSer2TI%2FAAAAAAAAAQE%2Ftz-qsBxNIz0%2Fs1600%2Fkelvingrove-park-summer.jpeg&f=1&nofb=1",
        "description": "The River Kelvin runs through the West End's large and attractive park which hosts festivals and events throughout the year.",
        "location": "Otago Street, Glasgow",
        "price_range": "FR",
        "family_friendly": True,
        "disabled_access": True,
        "parking": False,
        "multi_language": True,
        "tags": ["Park", "Cultural Landmark",],
    },
}
