tags = {
    "Museum": [],
    "Festival": [],
    "Art Gallery": [],
    "Historic": [],
    "Cultural Landmark": [],
    "Natural Landmark": [],
    "Park": [],
    "Sports": [],
    "Monument": [],
    "Event":[],
    "Free": ["Cheap", "Moderate", "Expensive"],
    "Cheap": ["Free", "Moderate", "Expensive"],
    "Moderate": ["Free", "Cheap", "Expensive"],
    "Expensive": ["Free", "Cheap", "Moderate"],
    "Family-friendly": [],
    "Disabled Access": [],
    "Parking": [],
    "Multi-language": [],
}
